In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\nanda\appdata\local\programs\python\python312\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nanda\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nanda\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\nanda\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\nanda\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
country_series_metadata = pd.read_csv(r"C:\Users\Nanda\OneDrive\Documents\International_Debt_analysis_dataset\Country_Series_Metadata.csv",encoding_errors="ignore")

In [5]:
country_series_metadata.head()

,Type,Country Code,Series Code,Description
0,Country-Series,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
1,Country-Series,Afghanistan (AFG),"Population, total (SP.POP.TOTL)",Data source: United Nations World Population P...
2,Country-Series,Afghanistan (AFG),"External debt stocks, total (DOD, current US$)...","Long-term public and publicly guaranteed, long..."
3,Country-Series,Angola (AGO),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed debt ...
4,Country-Series,Angola (AGO),"Population, total (SP.POP.TOTL)",Data source: United Nations World Population P...

In [6]:
country_series_metadata.describe()

,Type,Country Code,Series Code,Description
count,375,375,375,375
unique,1,131,7,130
top,Country-Series,India (IND),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
freq,375,6,127,127

In [7]:
country_series_metadata.shape

(375, 4)

In [8]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\nanda\appdata\local\programs\python\python312\lib\site-packages (2.0.52)
Requirement already satisfied: pymysql in c:\users\nanda\appdata\local\programs\python\python312\lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\nanda\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nanda\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
from sqlalchemy import create_engine

In [10]:
engine = create_engine(
    "mysql+pymysql://root:test1234@127.0.0.1:3306/intdebtdetails"
)

In [11]:
country_series_metadata.to_sql(name="country_series_meta",con=engine,if_exists="replace",index=False)

375

In [12]:
allcountriesdata = pd.read_csv(r"C:\Users\Nanda\OneDrive\Documents\International_Debt_analysis_dataset\IDS_ALLCountries_Data.csv"
                               ,encoding_errors="ignore")

In [13]:
allcountriesdata.head()

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,2000,2001,2002,2003,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
len(allcountriesdata['Country Name'].unique())

137

In [15]:
allcountriesdata[['Counterpart-Area Name','Counterpart-Area Code']].value_counts

<bound method DataFrame.value_counts of       Counterpart-Area Name Counterpart-Area Code
0                     World                   WLD
1                     World                   WLD
2                     World                   WLD
3                     World                   WLD
4                     World                   WLD
...                     ...                   ...
62978                   NaN                   NaN
62979                   NaN                   NaN
62980                   NaN                   NaN
62981                   NaN                   NaN
62982                   NaN                   NaN

[62983 rows x 2 columns]>

In [16]:
allcountriesdata.drop(['Counterpart-Area Name','Counterpart-Area Code'],inplace=True,axis=1)

In [17]:
allcountriesdata.tail(20)

,Country Name,Country Code,Series Name,Series Code,2000,2001,2002,2003,2004,2005,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
62963,Zimbabwe,ZWE,"Residual, debt stock-flow reconciliation (curr...",DT.DOD.RSDL.CD,3.792271e+06,-2.834801e+07,5.434528e+07,1.026152e+07,1.816150e+07,1.405830e+07,...,-1.478546e+06,-6.622524e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62964,Zimbabwe,ZWE,Short-term debt (% of total external debt),DT.DOD.DSTC.ZS,1.435870e+01,1.507900e+01,1.406910e+01,1.796230e+01,2.044840e+01,2.367380e+01,...,2.705480e+01,2.754250e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62965,Zimbabwe,ZWE,Technical cooperation grants (current US$),BX.GRT.TECH.CD.DT,7.433000e+07,7.713000e+07,6.407000e+07,6.106000e+07,5.414000e+07,6.458000e+07,...,3.882098e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62966,Zimbabwe,ZWE,Total amount of debt rescheduled (current US$),DT.TXR.DPPG.CD,NaN,0.000000e+00,NaN,8.234989e+05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62967,Zimbabwe,ZWE,Total change in external debt stocks (current ...,DT.DOD.DECT.CD.CG,-4.561898e+08,-1.597213e+08,3.486875e+08,6.570790e+08,3.747801e+08,-4.786023e+08,...,4.277514e+08,-1.447938e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62968,Zimbabwe,ZWE,"Total debt service (% of exports of goods, ser...",DT.TDS.DECT.EX.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.951607e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62969,Zimbabwe,ZWE,Total external debt per capita (US$),DT.DOD.DECT.PC.CD,3.335519e+02,3.179859e+02,3.437875e+02,3.934381e+02,4.194959e+02,3.772072e+02,...,8.903184e+02,8.659022e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62970,Zimbabwe,ZWE,Total reserves (% of total external debt),FI.RES.TOTL.DT.ZS,6.013530e+00,2.422245e+00,2.552179e+00,2.252133e+00,4.326015e+00,2.312493e+00,...,7.555371e-01,3.365870e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62971,Zimbabwe,ZWE,"Total reserves (includes gold, current US$)",FI.RES.TOTL.CD,2.385337e+08,9.221233e+07,1.060579e+08,1.083875e+08,2.244095e+08,1.088916e+08,...,1.099196e+08,4.848111e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62972,Zimbabwe,ZWE,Total reserves in months of imports,FI.RES.TOTL.MO,NaN,NaN,NaN,NaN,NaN,NaN,...,1.228685e-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62973,Zimbabwe,ZWE,"Undisbursed external debt, official creditors ...",DT.UND.OFFT.CD,9.522543e+08,6.726103e+08,4.416524e+08,4.721825e+08,3.814633e+08,2.648020e+08,...,7.647331e+08,6.881084e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62974,Zimbabwe,ZWE,"Undisbursed external debt, private creditors (...",DT.UND.PRVT.CD,9.075099e+07,6.973488e+07,5.350670e+07,3.524154e+07,3.385817e+07,2.590525e+07,...,6.657338e+06,6.350490e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62975,Zimbabwe,ZWE,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,1.043005e+09,7.423452e+08,4.951591e+08,5.074240e+08,4.153215e+08,2.907072e+08,...,7.713904e+08,6.944589e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62976,Zimbabwe,ZWE,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.US.CD,2.806598e+08,2.619515e+08,2.802460e+08,3.015538e+08,2.932067e+08,1.105069e+08,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62977,Zimbabwe,ZWE,"Use of IMF credit and SDR allocations(DOD, cur...",DT.DOD.DIMF.CD,2.939495e+08,2.747702e+08,2.941131e+08,3.167107e+08,3.090474e+08,1.250854e+08,...,1.363159e+09,1.325023e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62981,Data from database: International Debt Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62982,Last Updated: 12/03/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
allcountriesdata.describe()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
count,4.949000e+04,4.943400e+04,4.926200e+04,4.900100e+04,4.919500e+04,4.913700e+04,4.939400e+04,4.964500e+04,4.949700e+04,4.976800e+04,...,5.064100e+04,5.059000e+04,1.285500e+04,1.276000e+04,1.262200e+04,1.243200e+04,1.213800e+04,1.196700e+04,1.177100e+04,1.156600e+04
mean,3.632014e+09,3.589615e+09,3.659750e+09,4.109777e+09,4.536444e+09,4.738496e+09,5.190393e+09,6.182575e+09,6.752879e+09,6.849177e+09,...,1.649637e+10,1.736519e+10,6.308260e+09,5.571382e+09,5.184003e+09,4.809777e+09,4.085452e+09,5.141240e+09,3.242091e+09,2.706323e+09
std,5.292695e+10,5.308864e+10,5.449395e+10,6.107004e+10,7.054690e+10,8.035767e+10,9.357806e+10,1.147883e+11,1.365185e+11,1.357978e+11,...,3.389385e+11,3.512324e+11,3.737201e+10,3.200925e+10,2.969469e+10,2.622276e+10,2.201532e+10,3.087435e+10,1.687863e+10,1.380838e+10
min,-8.487669e+10,-5.573282e+10,-7.292274e+10,-5.500037e+10,-3.736228e+10,-7.343440e+10,-7.145644e+10,-5.255350e+10,-6.940197e+10,-4.432376e+10,...,-2.590000e+11,-2.320000e+11,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.112442e+00,3.541816e-01,7.421391e-01,1.116054e-01,5.356484e-01,7.739000e-01,9.361400e-01,2.862026e+00,3.052400e+00,5.876775e+00,...,0.000000e+00,0.000000e+00,1.819800e+07,1.736757e+07,1.692255e+07,1.508966e+07,1.359342e+07,1.182594e+07,1.033100e+07,8.062213e+06
50%,9.046966e+06,8.033068e+06,7.674301e+06,8.706365e+06,9.689430e+06,9.915805e+06,1.046313e+07,1.172750e+07,1.261500e+07,1.515973e+07,...,3.397000e+07,3.286379e+07,1.747302e+08,1.683518e+08,1.612748e+08,1.386245e+08,1.220880e+08,1.077675e+08,9.936185e+07,8.007778e+07
75%,1.725729e+08,1.660500e+08,1.715300e+08,1.868751e+08,2.174472e+08,2.195815e+08,2.196477e+08,2.781230e+08,2.915208e+08,3.518703e+08,...,7.984620e+08,8.363163e+08,1.275588e+09,1.228297e+09,1.142909e+09,9.780040e+08,8.999615e+08,7.999839e+08,8.112449e+08,6.457404e+08
max,5.440000e+12,5.450000e+12,5.560000e+12,6.220000e+12,7.290000e+12,8.580000e+12,1.010000e+13,1.250000e+13,1.490000e+13,1.490000e+13,...,3.680000e+13,3.820000e+13,1.170000e+12,1.000000e+12,9.180000e+11,7.740000e+11,6.570000e+11,7.330000e+11,4.810000e+11,3.820000e+11

In [19]:
allcountriesdata['Country Name'].isna().value_counts()

Country Name
False    62980
True         3
Name: count, dtype: int64

In [20]:
allcountriesdata.dropna(subset=['Country Name'],axis=0,inplace=True)

In [21]:
allcountriesdata['Country Name'].isna().value_counts()

Country Name
False    62980
Name: count, dtype: int64

In [22]:
allcountriesdata

,Country Name,Country Code,Series Name,Series Code,2000,2001,2002,2003,2004,2005,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
0,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.DPPG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.OFFT,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62975,Zimbabwe,ZWE,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,1.043005e+09,742345186.0,495159055.8,507424047.1,415321460.7,290707233.0,...,7.713904e+08,6.944589e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62976,Zimbabwe,ZWE,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.US.CD,2.806598e+08,261951544.4,280246014.7,301553836.0,293206735.0,110506868.6,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62977,Zimbabwe,ZWE,"Use of IMF credit and SDR allocations(DOD, cur...",DT.DOD.DIMF.CD,2.939495e+08,274770190.4,294113118.7,316710730.0,309047437.0,125085422.6,...,1.363159e+09,1.325023e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62981,Data from database: International Debt Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62982,Last Updated: 12/03/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
allcountriesdata.drop(allcountriesdata.tail(2).index,inplace=True,axis=0)

In [24]:
allcountriesdata.fillna(0,inplace=True)

,Country Name,Country Code,Series Name,Series Code,2000,2001,2002,2003,2004,2005,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
0,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.DPPG,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.OFFT,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.PRVT,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.DPPG,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.OFFT,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62973,Zimbabwe,ZWE,"Undisbursed external debt, official creditors ...",DT.UND.OFFT.CD,9.522543e+08,672610306.0,441652353.0,472182506.5,381463289.9,264801978.8,...,7.647331e+08,6.881084e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62974,Zimbabwe,ZWE,"Undisbursed external debt, private creditors (...",DT.UND.PRVT.CD,9.075099e+07,69734880.0,53506702.8,35241540.6,33858170.8,25905254.2,...,6.657338e+06,6.350490e+06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62975,Zimbabwe,ZWE,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,1.043005e+09,742345186.0,495159055.8,507424047.1,415321460.7,290707233.0,...,7.713904e+08,6.944589e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62976,Zimbabwe,ZWE,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.US.CD,2.806598e+08,261951544.4,280246014.7,301553836.0,293206735.0,110506868.6,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62977,Zimbabwe,ZWE,"Use of IMF credit and SDR allocations(DOD, cur...",DT.DOD.DIMF.CD,2.939495e+08,274770190.4,294113118.7,316710730.0,309047437.0,125085422.6,...,1.363159e+09,1.325023e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
allcountriesdata.to_sql(name='allcountriesdata',con=engine,if_exists="replace",index=False)

62978

In [26]:
footnotesMetadata = pd.read_csv(r"C:\Users\Nanda\OneDrive\Documents\International_Debt_analysis_dataset\IDS_FootNoteMetaData.csv",encoding_errors="ignore")

In [27]:
footnotesMetadata.drop('Type',axis=1,inplace=True)

In [28]:
footnotesMetadata.to_sql(name="footnotesMetaData",con=engine,if_exists="replace")

InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mysql+pymysql://root:***@127.0.0.1:3306/intdebtdetails): (footnotesMetaData)

In [ ]:
seriesmetadata = pd.read_csv(r"C:\Users\Nanda\OneDrive\Documents\International_Debt_analysis_dataset\IDS_SeriesMetaData.csv",encoding_errors="ignore")

In [ ]:
seriesmetadata

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,Limitations and exceptions,General comments
0,DT.GPA.DPPG,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
1,DT.GPA.OFFT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
2,DT.GPA.PRVT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
3,DT.GRE.DPPG,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
4,DT.GRE.OFFT,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
569,FI.RES.TOTL.MO,NaN,Total reserves in months of imports,Total reserves comprise holdings of monetary g...,Total reserves comprise holdings of monetary g...,"International Monetary Fund, International Fin...",Economic Policy & Debt: Balance of payments: R...,International Debt Statistics,Annual,Weighted average,NaN,NaN
570,DT.UND.OFFT.CD,NaN,"Undisbursed external debt, official creditors ...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN,NaN
571,DT.UND.PRVT.CD,NaN,"Undisbursed external debt, private creditors (...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN,NaN
572,DT.UND.DPPG.CD,NaN,"Undisbursed external debt, total (UND, current...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN,NaN
573,DT.DOD.DIMF.CD,NaN,"Use of IMF credit (DOD, current US$)",Use of IMF credit denotes members drawings on ...,Use of IMF Credit: Data related to the operati...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Debt ou...,International Debt Statistics,Annual,Sum,NaN,NaN

In [ ]:
seriesmetadata['License Type'] = seriesmetadata['License Type'].fillna("No")

In [ ]:
seriesmetadata

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,Limitations and exceptions,General comments
0,DT.GPA.DPPG,No,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
1,DT.GPA.OFFT,No,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
2,DT.GPA.PRVT,No,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
3,DT.GRE.DPPG,No,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
4,DT.GRE.OFFT,No,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
569,FI.RES.TOTL.MO,No,Total reserves in months of imports,Total reserves comprise holdings of monetary g...,Total reserves comprise holdings of monetary g...,"International Monetary Fund, International Fin...",Economic Policy & Debt: Balance of payments: R...,International Debt Statistics,Annual,Weighted average,NaN,NaN
570,DT.UND.OFFT.CD,No,"Undisbursed external debt, official creditors ...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN,NaN
571,DT.UND.PRVT.CD,No,"Undisbursed external debt, private creditors (...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN,NaN
572,DT.UND.DPPG.CD,No,"Undisbursed external debt, total (UND, current...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN,NaN
573,DT.DOD.DIMF.CD,No,"Use of IMF credit (DOD, current US$)",Use of IMF credit denotes members drawings on ...,Use of IMF Credit: Data related to the operati...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Debt ou...,International Debt Statistics,Annual,Sum,NaN,NaN

In [ ]:
seriesmetadata[['Limitations and exceptions','General comments']].isna().value_counts()

Limitations and exceptions  General comments
True                        True                566
                            False                 7
False                       False                 1
Name: count, dtype: int64

In [ ]:
seriesmetadata.to_sql(name="seriesmetadata",con=engine,if_exists="replace",index=False)

574

In [ ]:
years_col= [col for col in allcountriesdata.columns if col.isdigit()]

In [33]:
allcountriesdata.rename(columns={col: f"y{col}" for col in years_col}, inplace=True)

In [34]:
allcountriesdata

,Country Name,Country Code,Series Name,Series Code,y2000,y2001,y2002,y2003,y2004,y2005,...,y2023,y2024,y2025,y2026,y2027,y2028,y2029,y2030,y2031,y2032
0,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.DPPG,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.OFFT,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.PRVT,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.DPPG,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.OFFT,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62973,Zimbabwe,ZWE,"Undisbursed external debt, official creditors ...",DT.UND.OFFT.CD,9.522543e+08,672610306.0,441652353.0,472182506.5,381463289.9,264801978.8,...,7.647331e+08,6.881084e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62974,Zimbabwe,ZWE,"Undisbursed external debt, private creditors (...",DT.UND.PRVT.CD,9.075099e+07,69734880.0,53506702.8,35241540.6,33858170.8,25905254.2,...,6.657338e+06,6.350490e+06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62975,Zimbabwe,ZWE,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,1.043005e+09,742345186.0,495159055.8,507424047.1,415321460.7,290707233.0,...,7.713904e+08,6.944589e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62976,Zimbabwe,ZWE,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.US.CD,2.806598e+08,261951544.4,280246014.7,301553836.0,293206735.0,110506868.6,...,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62977,Zimbabwe,ZWE,"Use of IMF credit and SDR allocations(DOD, cur...",DT.DOD.DIMF.CD,2.939495e+08,274770190.4,294113118.7,316710730.0,309047437.0,125085422.6,...,1.363159e+09,1.325023e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
from international_debt_analyis_project_Pandas_Streamlit import databaseconnector

ModuleNotFoundError: No module named 'mysql'